### ISSUE TITLE
Player Team Value does not include upgrades

### ISSUE THREAD

**Issue by DerkG** [BSData/bloodbowl#51] opened 2021-11-12 09:30 UTC
**Describe the bug**
In league play, tge current team value of players shoulf go up based on the selected upgrades. Currently SPP spend is tracked, but TV impacy is not.

**To Reproduce**
1) give SPP to player
2) spend SPP on improvements
3) check impact on (C)TV

**Expected behavior**
(C)TV should go up in accordance with table on page 72 of the rule book.

**Comment by shaner11** [comment] 2021-11-13 01:54
Duplicate of #47

**Closed by shaner11** 2021-11-13 01:54 UTC
Labels: bug
