### ISSUE TITLE
[Anon] Bug report: College of Metal.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/bloodbowl#63] opened 2022-07-21 22:57 UTC
**File:** College of Metal.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When I try to make a collage of metal team, I can set the TV limit and name it but once I got to create it, it takes a bit to load and then BattleScribe straight up crashes and I have to reopen the app and the list does not get created.

**Comment by shaner11** [comment] 2022-07-23 08:29
This crash was caused by an error in the Goblin Bruiser Journeyman entry causing it to include a Goblin Bruiser Journeyman instead of an injuries menu. This caused the recurring creation of infinite Goblin Bruiser Journeymen until all memory was used. This has been resolved in the latest update. Your memory will no longer be flooded by endless goblins.

**Closed by shaner11** 2022-07-23 08:29 UTC
