### ISSUE TITLE
[Anon] Bug report: Blood Bowl.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/bloodbowl#58] opened 2022-06-02 17:08 UTC
**File:** Blood Bowl.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Advancements for players have disappeared. And the option to add advancements has gone so they cannot be re added.

**Comment by shaner11** [comment] 2022-06-04 02:49
Duplicate of #57

**Closed by shaner11** 2022-06-04 02:49 UTC
