### ISSUE TITLE
[Anon] Bug report: Blood Bowl.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/bloodbowl#50] opened 2021-10-18 11:21 UTC
**File:** Blood Bowl.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Team value does not increase, when you advance a player.

**Comment by shaner11** [comment] 2021-11-13 01:54
Duplicate of #47

**Closed by shaner11** 2021-11-13 01:54 UTC
