### ISSUE TITLE
Cost in Ogres Team. Pull request create.

### ISSUE THREAD

**Issue by Vic40k** [BSData/bloodbowl#66] opened 2022-07-27 20:41 UTC
Hello!
I found bugs in Ogres team and create my own fix https://github.com/BSData/bloodbowl/pull/65

Fix wrong cost view for Blocker and Runt Punter (145 000 instead of 140 000 and 140 000 instead of 145 000).
Fix Gnoblar TV value. Gnoblar doesn`t have cost, set 15 000.

**Comment by shaner11** [comment] 2022-08-09 06:32
This has been fixed in in v3.5.3 (Ogre Team v32).

Both of the Ogre profiles have been swapped, and I double checked there were no issues with the options available to those player types to be safe.

Gnoblars costing 0 is intentional behavior in league play. This represents the Low Cost Linemen rule removing the hiring fee of linemen players from CTV. As always, it is up to the player to modify their treasury as they purchase new players. There was a bug preventing the cost being added back in exhibition rosters which has been fixed, so this should work as intended now.

**Closed by shaner11** 2022-08-09 06:32 UTC
Labels: bug

**Comment by Vic40k** [comment] 2022-08-14 23:08
Thank you!
