### ISSUE TITLE
[Anon] Bug report: Ogres.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/bloodbowl#67] opened 2022-08-02 20:25 UTC
**File:** Ogres.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The stats table (abilities and passing stat) of the ogre blocker player and the runt punter player are exchanged with each other except with the hiring fee.

**Comment by shaner11** [comment] 2022-08-09 06:26
Duplicate of #66

**Closed by shaner11** 2022-08-09 06:26 UTC
