### ISSUE TITLE
[Anon] Bug report: Blood Bowl.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/bloodbowl#49] opened 2021-09-26 12:42 UTC
**File:** Blood Bowl.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** TV of players not increasing when picking an advancement.

**Comment by shaner11** [comment] 2021-11-13 01:53
Duplicate of #47

**Closed by shaner11** 2021-11-13 01:53 UTC
